# AKS Desktop - Kubernetes Service for nginx
# Generated on 2025-09-16T21:52:43.508Z
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: nginx-project
    kubernetes.azure.com/generator: aks-desktop
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nginx
